﷽
NotSoSuper/NotSoBot pull request #24
Opened 2017-11-04 17:24 UTC by RuyiLi

﷽﷽﷽

2017-11-29 19:52 UTC, ConnorMcF approved these changes
Literally unplayable, this fix resolves all issues and fixes bot uptime.

2019-03-17 23:18 UTC, matmen approved these changes

2019-03-17 23:43 UTC, ConnorMcF requested changes

2019-03-17 23:43 UTC, ConnorMcF commented on README.md
> +The MySQL database scheme is included in `discord.sql`, you will have to reverse or replace the environmental variables in the code for proper results.
whom say environmental variables, environment variables please and thanks

2023-08-17 20:42 UTC, closed without merging

2023-08-19 19:31 UTC, Dominic18 commented
You can go fuck yourself.

On Thu, Aug 17, 2023, 4:43 PM Roy Li ***@***.***> wrote:

> Closed #24 <https://github.com/NotSoSuper/NotSoBot/pull/24>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NotSoSuper/NotSoBot/pull/24#event-10123763604>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALGKOC4Q5GMNXHNQGM7DH6DXVZ65HANCNFSM4ECIK74A>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-08-19 20:28 UTC, RuyiLi commented
huh? 💀